### PR TITLE
alert system component

### LINKED ISSUE #36: Create alert system components
This issues is part of ODHACK 10.0, apply via the platform

Description:

Create components to display alert messages for both success and error scenarios. Ensure the components are customizable, user-friendly, and able to handle different types of messages effectively.

Looking forward to seeing your great work!

### PR DESCRIPTION
**Pull request by Jemiiah**
Fix #36

### CODE REVIEW

**Comment by zintarh** [comment]
@Jemiiah Please can you fix CI

**Comment by Jemiiah** [comment]
alright ma'am

**Comment by zintarh** [comment]
@Jemiiah Could you please provide a screenshot showing that this issue has been resolved?

**Review by zintarh — APPROVED** [review]
Lgtm

**Pull request merged**
