### PR TITLE
fix: add bg image

### PR DESCRIPTION
**Pull request by Kingsuite**
hey @zintarh kindly review :) #43

### CODE REVIEW

**Review by zintarh — COMMENTED** [review]
Please fix the navbar 
Screenshot 2024-11-29 at 3 58 34 AM

**Review by zintarh — COMMENTED** [review]
Instead of using a single image as the background for the landing page, utilize three different images from Figma, assigning each image as the background for a separate section.

Screenshot 2024-11-29 at 4 01 12 AM

**Comment by Kingsuite** [comment]
hey @zintarh kindly review :)

**Review by zintarh — APPROVED** [review]
Lgtm

**Comment by Kingsuite** [comment]
hey @zintarh fixed the CI issues :)

**Pull request merged**
